# Generated by Django 5.1.3 on 2025-01-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='image/placeholder.png', null=True, upload_to='image'),
        ),
    ]
